spring.application.name=pos-mature-example

# JPA/Hibernate Properties
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=create-drop

# OpenAPI/Swagger Properties
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/api/openapi
springdoc.swagger-ui.path=/api/swagger